Finished altering preloaded hod models to be preloaded model blueprints. Tinker13 mock population is buggy:
HalotoolsError: The ``halo_table`` passed as a keyword argument to the mean_occupation method does not have the requested ``central_sfr_designation`` key