Current test suite has many, many failures. I made one single change: the signature to the constructor of HaloCatalog now has simname being set to sim_defaults.default_simname, whereas before this was simply a positional argument. This change alone triggers:
ImportError: cannot import name model_defaults